// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgbKU4Opi4QMbkD1ChW_vBMDjYuNDnF3o',
    appId: '1:610504886168:web:a5fc628b450c9db77e0ded',
    messagingSenderId: '610504886168',
    projectId: 'terra-iot',
    authDomain: 'terra-iot.firebaseapp.com',
    storageBucket: 'terra-iot.firebasestorage.app',
    measurementId: 'G-MYVNH12HNM',
    databaseURL:
        'https://terra-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX4UKZbiYijz89xe5ePbT9fMVdWPsW9FY',
    appId: '1:610504886168:android:6fcdd0cb8af71c177e0ded',
    messagingSenderId: '610504886168',
    projectId: 'terra-iot',
    storageBucket: 'terra-iot.firebasestorage.app',
    databaseURL:
        'https://terra-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiguvDiJAlCxTOz4sDSCyndecyTy5Aq9Y',
    appId: '1:610504886168:ios:e4532649d996e1457e0ded',
    messagingSenderId: '610504886168',
    projectId: 'terra-iot',
    storageBucket: 'terra-iot.firebasestorage.app',
    iosBundleId: 'com.example.terra',
    databaseURL:
        'https://terra-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiguvDiJAlCxTOz4sDSCyndecyTy5Aq9Y',
    appId: '1:610504886168:ios:e4532649d996e1457e0ded',
    messagingSenderId: '610504886168',
    projectId: 'terra-iot',
    storageBucket: 'terra-iot.firebasestorage.app',
    iosBundleId: 'com.example.terra',
    databaseURL:
        'https://terra-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgbKU4Opi4QMbkD1ChW_vBMDjYuNDnF3o',
    appId: '1:610504886168:web:9322e2156d2e49d37e0ded',
    messagingSenderId: '610504886168',
    projectId: 'terra-iot',
    authDomain: 'terra-iot.firebaseapp.com',
    storageBucket: 'terra-iot.firebasestorage.app',
    measurementId: 'G-HNBCZ2NSLG',
    databaseURL:
        'https://terra-iot-default-rtdb.asia-southeast1.firebasedatabase.app',
  );
}
